#!/bin/bash

clock() 
{
	date +%H:%M:%S
}

battery()
{
	cat /sys/class/power_supply/BAT0/capacity
}

packages()
{
	pacman -Q | wc -l
}

while true; do
	BAR_INPUT="%{c}Battery Life : $(battery)% |  Time: $(clock) | Total Packages Installed: $(packages)"
	echo $BAR_INPUT
	sleep 1
done
